spring:
  application:
    name: api-requerimiento-rrhh
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
    password: Peru123.
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/rrhhcompany
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
server:
  servlet:
    context-path: /rrhh
  port: 0
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/